# Evaluate Word Dispersion Scores on the GENIA Corpus Data

Authors: Samuel Sarria Hurtado and Paul Sheridan

Last update: 2025-06-01

Description: Evaluate the following word dispersion scores on the Genia corpus data:
- Inverse Document Frequency (IDF)
- Inverse Collection Frequency (ICF)
- Chi-square (Chisq)
- Church and Gale (CG)
- Irvine and Callison-Burch (ICB)
- Derivation of Proportions (DoP)
- Residual ICF (RICF)
- Weighted RICF (wRICF)

Calculate P@k scores for each scoring function using the GENIA terms as ground truth. Also, evaluate scoring functions for their ability to filter out stop words.

## Imports

In [1]:
# Load required libraries.
import sys
import json
import pandas as pd
sys.path.append('../0-base-functions/') # Add path to Python function files to system path
import wordstats
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import random
import scipy
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from io import StringIO
from numpy import nan

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pasheridan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

## Preliminaries

Read in GENIA corpus and stopwords lists.

In [2]:
# Load the GENIA corpus.
json_genia_path = '../1-preprocessing/GENIAcorpus3.02-preprocessed.json'

with open(json_genia_path, "r") as j:
  genia = json.loads(j.read())

# Load GENIA keywords.
keyword_genia_path = '../1-preprocessing/GENIAcorpus3.02-keywords.tsv'

with open(keyword_genia_path, "r") as c:
  key_words = pd.read_csv(c, sep='\t')
all_genia_words = key_words.lex.to_numpy()

# Load Terrier stopwords.
terrier_path = '../0-data-raw/terrier-stopwords.txt'
terrier_stopwords = np.loadtxt(terrier_path, dtype=str)

# Load MyISAM stopwords.
myisam_path = '../0-data-raw/myisam-stopwords.txt'

with open(myisam_path, 'r') as t:
  myisam_txt = StringIO(t.read() + '  NA  NA')

myisam_stopwords = np.loadtxt(myisam_txt, dtype=str)
myisam_stopwords = np.reshape(myisam_stopwords, (545, ))
nas = np.where(myisam_stopwords == 'NA')[0]
myisam_stopwords = np.delete(myisam_stopwords, nas).tolist()

## Construct GENIA Corpus Vocabulary

This is the vocabulary input for the count vectorizer below.

In [3]:
# Custom function so the Count vectorizer won't ignore any words.
def analyzer_custom(doc):
  return doc.split()
    
# Construct the GENIA vocabulary.
pre_vocab = []
for i in range(len(genia)):
  pre_vocab.append(genia[i].split())

vocab = []
for i in range(len(pre_vocab)):
  for j in range(len(pre_vocab[i])):
    vocab.append(pre_vocab[i][j])

# Sort vocabulary list in reproducible, random order.
random.seed(641369)
vocab = sorted(list(set(vocab)))
random.shuffle(vocab)

# Initialize collection object.
counter = CountVectorizer(lowercase=False, vocabulary=vocab, analyzer=analyzer_custom)
collection = counter.transform(genia)

# Check first 10 vocabulary terms.
print(vocab[:10])

['inefficient_NF-kappaB_activation_lex', 'TRP_lex', 'proposing', 'PDX-1/IPF1/STF-1_lex', 'heterologous', 'hCLEO_element_lex', 'unrestricted', 'anti-LPS_mAb_lex', 'germline_TaqI_restriction_fragment_length_polymorphism_lex', 'normal_leukocyte_lex']

## Word Dispersion Score Evaluation

Calculate bag-of-words model word statistics.

In [4]:
m = len(vocab)
d = collection.shape[0]
N_i = wordstats.get_Ni(collection)
N_j = wordstats.get_Nj(collection)
N = wordstats.get_N(N_j)
B_ij = wordstats.get_Bij(collection)
B_i = wordstats.get_Bi(B_ij)
B_j = wordstats.get_Bj(B_ij)
DF = wordstats.get_DF(B_i, d)
CF = wordstats.get_CF(N_i)
nij_by_nj = wordstats.get_nij_by_nj(collection, N_j)
thetas = np.array(range(1, max(N_i.A[0]) + 1))/N
opt_thetas = wordstats.get_opt_thetas(N, m, d, N_i, N_j, B_i, thetas)

Evaluate word dispersion scores.

In [5]:
IDF = wordstats.get_IDF(DF)
ICF = wordstats.get_ICF(CF)
Chisq = wordstats.get_Chisq(collection)
CG = wordstats.get_CG(N_i, B_i)
ICB = wordstats.get_ICB(nij_by_nj, B_i)
DoP = wordstats.get_DoP(collection, N_i, N_j, N)
RICF = wordstats.get_RICF(opt_thetas, N, ICF)
wRICF = wordstats.get_wRICF(RICF, B_i)

/Users/pasheridan/Desktop/github-repos/bursty-term-measure/genia/3-tables/../0-base-functions/wordstats.py:209: RuntimeWarning: divide by zero encountered in log
  return -np.log(chisq_values)

## Compare Word Dispersion Measures

### Preliminary Dataframes

In [8]:
# Create word dispersion score data frame.
dta = {'term': vocab, 'IDF': IDF.A[0], 'ICF': ICF.A[0], 'Chi-sq': Chisq, 'CG': CG.A[0], 'ICB': ICB.A[0], 'DoP': DoP.A[0], 'RICF': RICF.A[0], 'wRICF': wRICF}
scores_df = pd.DataFrame(data=dta)

# Print scores to console.
print(scores_df)

# Save scores to TSV.
scores_df.to_csv('word-dispersion-scores.tsv', sep='\t')

                                       term       IDF        ICF    Chi-sq  \
0      inefficient_NF-kappaB_activation_lex  7.600902  12.800954  0.701595
1                                   TRP_lex  7.600902  11.414659       inf
2                                 proposing  7.600902  12.800954  0.701595
3                      PDX-1/IPF1/STF-1_lex  7.600902  12.800954  0.701595
4                              heterologous  5.203007  10.403058  0.582004
...                                     ...       ...        ...       ...
40799                                    ss  7.600902  12.800954  0.701595
40800          competition_EMS_analysis_lex  7.600902  12.800954  0.701595
40801          B-cell-specific_B29_gene_lex  7.600902  12.800954  0.701595
40802             healthy_virus_carrier_lex  7.600902  12.800954  0.701595
40803          PMN-mediated_lung_injury_lex  7.600902  12.800954  0.701595

        CG          ICB       DoP      RICF         wRICF
0      1.0   159.000000 -0.000439 -0.000251 -8.215312e-09
1      4.0  1048.000000 -0.000723  1.386043  4.537858e-05
2      1.0   218.000000 -0.000601 -0.000251 -8.215312e-09
3      1.0   212.000000 -0.000585 -0.000251 -8.215312e-09
4      1.0   201.909091 -0.006126 -0.002999 -2.039844e-05
...    ...          ...       ...       ...           ...
40799  1.0   227.000000 -0.000626 -0.000251 -8.215312e-09
40800  1.0   223.000000 -0.000615 -0.000251 -8.215312e-09
40801  1.0   188.000000 -0.000519 -0.000251 -8.215312e-09
40802  1.0   104.000000 -0.000287 -0.000251 -8.215312e-09
40803  1.0   174.000000 -0.000480 -0.000251 -8.215312e-09

[40804 rows x 9 columns]

In [9]:
# Create ranks data frame.
sorted_indices = []
cols = scores_df.columns.values.tolist()
for col in cols:
  if col == 'term':
    sorted_indices.append(np.array(scores_df['term']))
  else:
    a = np.array(scores_df[[col]])
    sorted_indices.append(len(a) - scipy.stats.rankdata(a, method='ordinal', nan_policy='omit').astype(int))

sorted_indices = np.array(sorted_indices)
m_t_pair = zip(cols, sorted_indices)
measures_indices = dict(m_t_pair)
measures_indices_df = pd.DataFrame(measures_indices)

In [10]:
# Organize stopwords.
st_words = stopwords.words('english')
all_stopwords = [st_words, terrier_stopwords, myisam_stopwords]
lst_stopwords = []
for i in range(len(all_stopwords)):
  for j in range(len(all_stopwords[i])):
    lst_stopwords.append(all_stopwords[i][j])

lst_stopwords = set(lst_stopwords)
vocab_st_words = list(set(vocab).intersection(set(lst_stopwords)))
vocab_st_words_in = []
for i in range(len(measures_indices_df['term'])):
  if measures_indices_df['term'][i] in vocab_st_words:
    vocab_st_words_in.append(i)

vocab_st_words_in = np.array(vocab_st_words_in)

table_of_stop_words = measures_indices_df[measures_indices_df['term'].isin(vocab_st_words)]

### Statistical Analysis of Measures

In [11]:
# Each measure has a unique ranking for a word in the corpus. The smaller the ranking
# the higher the dispersion. These are the quartiles of the rankings for all measures.
quantiles = []
for col in cols:
  if col == 'term': continue
  quantiles.append(table_of_stop_words[col].quantile([0, 0.25, 0.5, 0.75, 1]))

quantiles_df = pd.DataFrame(quantiles)
display(quantiles_df)

          0.00     0.25     0.50     0.75     1.00
IDF      971.0  37077.0  39692.0  40549.0  40803.0
ICF      855.0  35657.0  39511.0  40514.0  40803.0
Chi-sq   601.0   8022.0   8796.0  39170.0  40802.0
CG        18.0   7750.0   8755.0  23068.0  40598.0
ICB       69.0  11310.0  16852.0  22435.0  40513.0
DoP      311.0  37084.0  39692.0  40550.0  40803.0
RICF    2093.0   8122.0   8810.0  39352.0  40802.0
wRICF      7.0    517.0   2774.0  39352.0  40801.0

In [12]:
# Write data frame to CSV.
quantiles_df.to_csv('quartiles.csv')

In [13]:
sorted_terms = []
measures = cols[1:]
for measure in measures:
  sorted_terms.append(np.array(scores_df[['term', measure]].sort_values(measure, ascending=False)['term']))

sorted_terms = np.array(sorted_terms)
measure_term_pair = zip(measures, sorted_terms)
sorted_measures = dict(measure_term_pair)

In [14]:
def top_k(dct, k):
  keys = dct.keys()
  values = []
  for key in keys:
    values.append(dct[key][:k])
  keys_values_pair = zip(keys, values)
  return dict(keys_values_pair)

In [15]:
# These are the top 10 most dispersed words as ranked by each measure.
top_10_terms = pd.DataFrame(top_k(sorted_measures, 10))
top_10_terms

,IDF,ICF,Chi-sq,CG,ICB,DoP,RICF,wRICF
0,inefficient_NF-kappaB_activation_lex,inefficient_NF-kappaB_activation_lex,iNOS_lex,Bcl-6_lex,Bcl-6_lex,extrathymic_development_lex,Bcl-6_lex,NF-kappa_B_lex
1,p100-mediated_cytoplasmic_sequestration_lex,B-cell_maturation_pattern_lex,c-jun_RNA_lex,SMX_lex,TCRzeta_lex,interleukin-15_lex,SMX_lex,NF-kappaB_lex
2,Cox_analysis_lex,heterologous_DC-T-cell_syncytia_lex,LEF-1_lex,v-erbA_lex,ML-9_lex,thymus-derived_T-cell_homeostasis_lex,v-erbA_lex,patient_lex
3,B_cell_lineage_lex,CD4(+)_CD8(-)_CD3(+)_thymocyte_lex,I_kappaB_lex,ML-9_lex,AITL_lex,guardian,ML-9_lex,T_cell_lex
4,placental_clone_lex,betachain,transcript_deletion_lex,SHP1_lex,SHP1_lex,distinct_function_lex,SHP1_lex,LPS_lex
5,VAV_lex,JAK-1-deficient_HeLa_cell_lex,Jak1_expression_lex,beta-casein_lex,beta-casein_lex,plasma_cell_pathway_lex,beta-casein_lex,HIV-1_lex
6,Inv(16)(p13;q22)_lex,rosen,E3330_lex,p95vav_lex,A-myb_lex,B-lymphocyte_differentiation_lex,TCRzeta_lex,differentiation
7,RA-_and_VitD3-signaling_pathway_lex,COX-2_activity_lex,IKK-beta_lex,TCRzeta_lex,I_kappaB_lex,B-cell_commitment_lex,I_kappaB_lex,was
8,NF-kappa_B1_promoter_lex,GTP-bound_p21ras_lex,AZT_lex,EBNA-2_lex,SMX_lex,memory_B_cells_lex,p95vav_lex,p
9,cyclosporin_A-resistant_transactivation_lex,cytokine_pleiotropy_lex,selenium_lex,DM_lex,Rap1_protein_lex,memory_B-cell_pathway_lex,DM_lex,IL-2_lex

In [16]:
# Write data frame as a CSV.
top_10_terms.to_csv('top-10-terms.csv')

In [17]:
# Write full data frame as a CSV.
top_45000_terms = pd.DataFrame(top_k(sorted_measures, 45000))
top_45000_terms.to_csv('top-45000-terms.csv')

In [18]:
amino_acid_sems = ['G#amino_acid_monomer', 'G#peptide', 'G#protein_N/A',
              'G#protein_complex', 'G#protein_domain_or_region',
              'G#protein_family_or_group', 'G#protein_molecule',
              'G#protein_substructure', 'G#protein_subunit',
              'G#other_organic_compound', 'G#organic', 'G#inorganic', 'G#atom',
              'G#carbohydrate', 'G#lipid']
nucleotide_sems = ['G#nucleotide', 'G#polynucleotide', 'G#DNA_N/A',
        'G#DNA_domain_or_region', 'G#DNA_family_or_group', 'G#DNA_molecule',
        'G#DNA_substructure', 'G#RNA_N/A', 'G#RNA_domain_or_region',
        'G#RNA_family_or_group', 'G#RNA_molecule', 'G#RNA_substructure']
multi_cell_sems = ['G#virus', 'G#mono_cell', 'G#multi_cell', 'G#body_part', 'G#tissue']
cell_sems = ['G#cell_type', 'G#cell_component', 'G#cell_line',
         'G#other_artificial_source']
other_sems = ['G#other_name']

sem = np.array(key_words['sem'])
lex = np.array(key_words['lex'])
lex_sem_dct = dict(zip(lex, sem))

def get_color_words(lst_color):
  words = []
  for k, v in lex_sem_dct.items():
    if v in lst_color:
      words.append(k)
  return words

amino_acid = get_color_words(amino_acid_sems)
nucleotide = get_color_words(nucleotide_sems)
multi_cell = get_color_words(multi_cell_sems)
cell = get_color_words(cell_sems)
other = get_color_words(other_sems)

print('amino_acid words: ', len(amino_acid), 'nucleotide words: ', len(nucleotide),
      'multi_cell words: ', len(multi_cell), 'cell words: ', len(cell),
      'other words: ', len(other))

amino_acid words:  10155 nucleotide words:  5574 multi_cell words:  1444 cell words:  4051 other words:  10560

In [19]:
def count_words(lst, imp_words):
  counter = 0
  for x in lst:
    if x in imp_words:
      counter += 1
  return counter

def create_p_k(lst_words):
  measures = sorted_measures.keys()
  counts = [[], [], [], [], [], [], [], [], [], []]
  p_k_dct = dict(zip(measures, counts))
  for measure in p_k_dct.keys():
    for value in at_values:
      p_k_dct[measure].append(count_words(top_k(sorted_measures, value)[measure], lst_words)/value)
  result = pd.DataFrame(p_k_dct)
  result.index = at_values
  return result

In [20]:
# These are the p@k scores for the different categories of domain-specific words.
at_values = np.array([10, 50, 100, 500, 1000, 5000])
highlights = {'all': all_genia_words, 'amino_acid': amino_acid, 'nucleotide': nucleotide, 'multi_cell': multi_cell, 'cell': cell, 'other': other}
dfs = []
for k, v in highlights.items():
  dfs.append(create_p_k(v))
  print(k)
  display(dfs[-1])

all

        IDF    ICF  Chi-sq      CG     ICB     DoP    RICF   wRICF
10    1.000  0.800   1.000  1.0000  1.0000  0.9000  1.0000  0.7000
50    0.900  0.880   0.920  0.9600  1.0000  0.7800  1.0000  0.3400
100   0.900  0.880   0.950  0.9800  0.9800  0.7800  1.0000  0.2900
500   0.868  0.870   0.954  0.9820  0.9740  0.8260  0.9900  0.2960
1000  0.873  0.858   0.955  0.9800  0.9630  0.8530  0.9860  0.3500
5000  0.870  0.855   0.916  0.9278  0.8972  0.8752  0.9314  0.5882

amino_acid

         IDF     ICF  Chi-sq      CG     ICB     DoP   RICF   wRICF
10    0.1000  0.1000   0.700  1.0000  0.8000  0.1000  1.000  0.4000
50    0.2600  0.3000   0.420  0.7600  0.7000  0.2200  0.780  0.2200
100   0.2700  0.3000   0.490  0.8200  0.7500  0.1300  0.830  0.1900
500   0.2780  0.2420   0.524  0.6820  0.6220  0.2200  0.684  0.1840
1000  0.2730  0.2480   0.534  0.6420  0.5900  0.2530  0.650  0.2020
5000  0.2632  0.2462   0.429  0.4296  0.4114  0.2802  0.430  0.2666

nucleotide

         IDF    ICF  Chi-sq      CG     ICB     DoP   RICF   wRICF
10    0.2000  0.000  0.1000  0.0000  0.1000  0.0000  0.000  0.0000
50    0.0800  0.100  0.2000  0.1000  0.1200  0.1200  0.100  0.0000
100   0.0900  0.110  0.1600  0.1000  0.1000  0.1400  0.110  0.0000
500   0.1440  0.156  0.1540  0.1460  0.1460  0.1380  0.144  0.0200
1000  0.1420  0.145  0.1550  0.1360  0.1400  0.1400  0.135  0.0270
5000  0.1582  0.150  0.1516  0.1558  0.1482  0.1528  0.156  0.0812

multi_cell

         IDF     ICF  Chi-sq     CG     ICB     DoP   RICF   wRICF
10    0.1000  0.0000  0.0000  0.000  0.0000  0.0000  0.000  0.2000
50    0.0600  0.0400  0.0000  0.040  0.0400  0.0800  0.040  0.0400
100   0.0700  0.0300  0.0100  0.020  0.0200  0.0900  0.020  0.0300
500   0.0360  0.0480  0.0440  0.034  0.0320  0.0560  0.032  0.0220
1000  0.0350  0.0430  0.0420  0.036  0.0410  0.0530  0.036  0.0200
5000  0.0386  0.0348  0.0442  0.044  0.0412  0.0468  0.044  0.0336

cell

         IDF     ICF  Chi-sq      CG     ICB     DoP   RICF   wRICF
10    0.2000  0.3000  0.0000  0.0000  0.0000  0.1000  0.000  0.1000
50    0.1400  0.1800  0.0600  0.0000  0.0000  0.1600  0.020  0.0400
100   0.1400  0.1500  0.0900  0.0100  0.0200  0.1200  0.010  0.0400
500   0.1120  0.1220  0.0700  0.0360  0.0600  0.0900  0.042  0.0440
1000  0.1210  0.1150  0.0710  0.0610  0.0690  0.0920  0.059  0.0570
5000  0.1168  0.1204  0.0966  0.0986  0.0988  0.0946  0.100  0.0704

other

         IDF     ICF  Chi-sq      CG     ICB     DoP    RICF   wRICF
10    0.4000  0.4000  0.2000  0.0000  0.1000  0.7000  0.0000  0.0000
50    0.3600  0.2600  0.2400  0.0600  0.1400  0.2000  0.0600  0.0400
100   0.3300  0.2900  0.2000  0.0300  0.0900  0.3000  0.0300  0.0300
500   0.2980  0.3020  0.1620  0.0840  0.1140  0.3220  0.0880  0.0260
1000  0.3020  0.3070  0.1530  0.1050  0.1230  0.3150  0.1060  0.0440
5000  0.2932  0.3036  0.1946  0.1998  0.1976  0.3008  0.2014  0.1364

In [21]:
# Write the p@k tables to CSVs.
dfs[0].to_csv('p-at-k/all-semantic-classes.csv')
dfs[1].to_csv('p-at-k/amino-acid-semantic-classes.csv')
dfs[2].to_csv('p-at-k/nucleotide-semantic-classes.csv')
dfs[3].to_csv('p-at-k/multi-cell-semantic-classes.csv')
dfs[4].to_csv('p-at-k/cell-semantic-classes.csv')
dfs[5].to_csv('p-at-k/other-semantic-classes.csv')

OSError: Cannot save file into a non-existent directory: 'p-at-k'

In [30]:
# This cell counts how many words of each color there are in the corpus
color_words = [all_genia_words, amino_acid, nucleotide, multi_cell, cell, other]
color_words_counter = [0, 0, 0, 0, 0, 0]
for i in range(len(color_words)):
  for j in range(len(vocab)):
    if vocab[j] in color_words[i]:
      color_words_counter[i] += N_i.A[0][j]

names_of_words = ['all', 'amino_acid', 'nucleotide', 'multi_cell', 'cell', 'other']
color_word_count_zip = zip(names_of_words, color_words_counter)
counter_dict = dict(color_word_count_zip)
counter_dict

{'all': 90969,
 'amino_acid': 42478,
 'nucleotide': 11619,
 'multi_cell': 5247,
 'cell': 11626,
 'other': 19999}

In [31]:
# This cell counts the number of unique words of each color in the corpus
color_words_counter = [0, 0, 0, 0, 0, 0]
for i in range(len(color_words)):
  for j in range(len(vocab)):
    if vocab[j] in color_words[i]:
      color_words_counter[i] += 1

unique_word_count_zip = zip(names_of_words, color_words_counter)
unique_word_num_dict = dict(unique_word_count_zip)
unique_word_num_dict

{'all': 31784,
 'amino_acid': 10155,
 'nucleotide': 5574,
 'multi_cell': 1444,
 'cell': 4051,
 'other': 10560}