# GENIA Corpus Keyword Extraction with KeyBERT

Description: Extract GENIA Corpus abstract keywords using KeyBERT and calculate associated importance scores.

In [1]:
# Imports
import json
from keybert import KeyBERT
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pandas as pd

In [2]:
# Path to GENIA corpus abstracts
infile_path = '../1-preprocessing/GENIAcorpus3.02-preprocessed-merged.json'

# Load the JSON contents into a Python variable
with open(infile_path, 'r') as file:
    docs = json.load(file)

n_docs = len(docs)
print(n_docs)

2000

In [4]:
# Extract keywords with KeyBERT

# This vectorizer ensures that KeyBERT recognizes hyphens
vectorizer = CountVectorizer(token_pattern=r'(?u)\b[\w-]+\b')
kw_model = KeyBERT()
keywords_corpus = [] # Store a list of KeyBERT keywords, one list for each doc

# Extract keywords from each doc
for index, doc in enumerate(docs):
    if index < 3:
        print("------------------------------------------------------------------------")
        kw_out = kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words='english', top_n=25, highlight=True, vectorizer=vectorizer)
    else:
        kw_out = kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words='english', top_n=25, vectorizer=vectorizer)
    
    keywords_doc = []
   
    for kw in kw_out:
        keywords_doc.append(kw[0])
    
    keywords_corpus.append(keywords_doc)

------------------------------------------------------------------------

IL-2_gene_expression IL-2_gene and NF-kappa_B_activation NF-kappa_B through CD28 requires reactive oxygen
production by 5-lipoxygenase Activation of the CD28_surface_receptor CD28 provides a major costimulatory signal for
T_cell_activation resulting in enhanced production of interleukin-2 IL-2 and cell_proliferation In
primary_T_lymphocyte we show that CD28 ligation leads to the rapid intracellular formation of
reactive_oxygen_intermediate ROI which are required for CD28-mediated_activation CD28 of the NF-kappa_B
CD28-responsive_complex CD28 and IL-2_expression IL-2 Delineation of the CD28_signaling_cascade CD28 was found to
involve protein_tyrosine_kinase_activity protein_tyrosine_kinase followed by the activation of phospholipase_A2 and
5-lipoxygenase Our data suggest that lipoxygenase_metabolite lipoxygenase activate ROI_formation ROI which then
induce IL-2 expression via NF-kappa_B_activation NF-kappa_B These findings should be useful for
therapeutic_strategies and the development of immunosuppressants targeting the CD28_costimulatory_pathway CD28

------------------------------------------------------------------------

The peri-kappa_B_site mediates human_immunodeficiency_virus_type_2_enhancer_activation
human_immunodeficiency_virus_type_2_enhancer human_immunodeficiency_virus_type_2 in monocyte but not in T_cell
human_immunodeficiency_virus_type_2 HIV-2 like HIV-1 causes AIDS and is associated with AIDS cases primarily in
West Africa HIV-1 and HIV-2 display significant differences in nucleic_acid_sequence and in the natural history of
clinical disease Consistent with these differences we have previously demonstrated that the enhancer
promoter_region of HIV-2 functions quite differently from that of HIV-1 Whereas activation of the HIV-1_enhancer
HIV-1 following T-cell_stimulation is mediated largely through binding of the transcription_factor NF-kappa_B to
two adjacent kappa_B_site in the HIV-1_long_terminal_repeat HIV-1 activation of the HIV-2_enhancer HIV-2 in
monocyte and T_cell is dependent on four cis-acting_element a single kappa_B_site two purine-rich_binding_site PuB1
and PuB2 and a pets_site We have now identified a novel cis-acting_element within the HIV-2_enhancer HIV-2
immediately upstream of the kappa_B_site designated peri-kappa_B This site is conserved among isolates of HIV-2 and
the closely related simian_immunodeficiency_virus and transfection_assay show this site to mediate
HIV-2_enhancer_activation HIV-2_enhancer HIV-2 following stimulation of monocytic_cell_line but not T-cell_line
This is the first description of an HIV-2_enhancer_element HIV-2 which displays such monocyte specificity and no
comparable enhancer_element has been clearly defined for HIV-1 While a nuclear_factor s from both
peripheral_blood_monocyte monocyte and T_cell binds the peri-kappa_B_site electrophoretic_mobility_shift_assay
suggest that either a different protein binds to this site in monocyte versus T_cell or that the protein
recognizing this enhancer_element undergoes differential_modification in monocyte and T_cell thus supporting the
transfection data Further while specific constitutive binding to the peri-kappa_B_site is seen in monocyte
stimulation with phorbol_ester induces additional specific binding Understanding the monocyte-specific_function of
the peri-kappa_B_factor may ultimately provide insight into the different role monocyte and T_cell play in
HIV_pathogenesis

------------------------------------------------------------------------

E1A_gene_expression E1A_gene induces susceptibility to killing by NK_cell following immortalization but not
adenovirus_infection adenovirus of human_cell adenovirus_ Ad _infection adenovirus and E1A_transfection E1A were
used to model changes in susceptibility to NK_cell_killing caused by transient vs stable E1A_expression E1A in
human_cell Only stably transfected_target_cell exhibited cytolytic susceptibility despite expression of equivalent
levels of E1A_protein in Ad-infected_target The inability of E1A_gene products to induce cytolytic_susceptibility
during infection was not explained by an inhibitory effect of viral infection on otherwise susceptible target_cell
or by viral_gene effects on class_I_MHC_antigen_expression class_I_MHC_antigen on target_cell This differential
effect of E1A_expression E1A on the cytolytic phenotypes of infected and stably transfected human_cell suggests
that human_NK_cell NK_cell provide an effective immunologic barrier against the in vivo survival and
neoplastic_progression of E1A-immortalized_cell that may emerge from the reservoir of persistently_infected_cell in
the human_host

In [5]:
# Calculate KeyBERT keyword scores

# Flatten, extract, and alphebetize unique keywords
unique_raw_keywords = list({keyword for doc in keywords_corpus for keyword in doc})
unique_raw_keywords.sort()
n_unique_raw_keywords = len(unique_raw_keywords)

# Create master data frame
master_df = pd.DataFrame(data={
    'raw_keyword': unique_raw_keywords,
    'KeyBERT': np.zeros(n_unique_raw_keywords)
})

# Calculate keyword scores
for idx, raw_keyword in master_df['raw_keyword'].items():
    score = sum(1 for doc in keywords_corpus if raw_keyword in doc) / n_docs
    master_df.at[idx, 'KeyBERT'] = score


display(master_df)

                           raw_keyword  KeyBERT
0                                    0   0.0005
1                 000-molecular-weight   0.0005
2                       000_mw_antigen   0.0005
3                          000_protein   0.0005
4      0302_trans_class_ii_heterodimer   0.0005
...                                ...      ...
25887         zta_dna-binding_activity   0.0005
25888          zymogen_plasma_factor_x   0.0005
25889       zymogen_plasma_factors_vii   0.0005
25890             zymosan-treated_cell   0.0005
25891             zymosan_inducibility   0.0005

[25892 rows x 2 columns]

In [7]:
# Recover GENIA lexical units from raw keywords

# Read in GENIA data
genia_keyword_path = '../1-preprocessing/GENIAcorpus3.02-keywords.tsv'
genia_df = pd.read_csv(genia_keyword_path, sep="\t")

# Convert lexical units to lowercase and strip '_lex' postfix
genia_df['raw_keyword'] = genia_df['lex'].str.lower().str.removesuffix('_lex')

# Add scores for lexical units
result_df = pd.merge(master_df, genia_df, on='raw_keyword', how='outer')

# Replace NaN scores with 0
result_df['KeyBERT'] = result_df['KeyBERT'].fillna(0)

# Clean up resulting data frame
result_df.rename(columns={'lex': 'term'}, inplace=True)

# Condition: If 'term' == NaN, take 'raw_keyword'; otherwise keep 'term'
# Includes non-lexical term scores.
result_df['term'] = np.where(result_df['term'].isna(), result_df['raw_keyword'], result_df['term'])

# Replace any NaNs in the 'sem' column with an empty string
# Uses empty string for the semantic class of non-lexical terms
result_df['sem'] = result_df['sem'].fillna(str())

# Drop 'raw_keywords' column
result_df.drop(columns=['raw_keyword'], inplace=True)

# Reorder columns
result_df = result_df.reindex(columns=['term', 'sem', 'KeyBERT'])

# Write to TSV
result_df.to_csv('keybert-scores.tsv', sep='\t', index=False)

display(result_df)

,term,sem,KeyBERT
0,0,,0.0005
1,000-molecular-weight,,0.0005
2,000_mw_antigen,,0.0005
3,000_protein,,0.0005
4,0302_trans_class_ii_heterodimer,,0.0005
...,...,...,...
35845,nucleosomal_DNA_lex,G#DNA_family_or_group,0.0000
35846,human_immunodeficiency_virus_(HIV)_entry_lex,G#other_name,0.0000
35847,"transcription_factor,_activated_protein-1_lex",G#protein_molecule,0.0000
35848,protein_synthesis-independent_lex,G#other_name,0.0000
35849,calcium_channel_blocker_lex,G#other_organic_compound,0.0000