# GENIA Corpus Keyword Extraction with KeyBERT

Authors: Uyen "Rachel" Lai and Paul Sheridan

Description: Extract GENIA Corpus abstract keywords using KeyBERT and calculate associated importance scores.

In [23]:
# Imports
import json
from keybert import KeyBERT
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
import pandas as pd

In [26]:
# Path to GENIA corpus abstracts
infile_path = '../1-preprocessing/GENIAcorpus3.02-preprocessed-merged.json'

# Load the JSON contents into a Python variable
with open(infile_path, 'r') as file:
    docs = json.load(file)

n_docs = len(docs)
print(n_docs)

3

In [15]:
# Extract keywords with KeyBERT

# This vectorizer ensures that KeyBERT recognizes hyphens
vectorizer = CountVectorizer(token_pattern=r'(?u)\b[\w-]+\b')
kw_model = KeyBERT()
keywords_corpus = [] # Store a list of KeyBERT keywords, one list for each doc

# Extract keywords from each doc
for doc in docs:
    print("------------------------------------------------------------------------")
    kw_out = kw_model.extract_keywords(doc, keyphrase_ngram_range=(1, 1), stop_words='english', top_n=25, highlight=True, vectorizer=vectorizer)
    keywords_doc = []
   
    for kw in kw_out:
        keywords_doc.append(kw[0])
    
    keywords_corpus.append(keywords_doc)

------------------------------------------------------------------------

IL-2_gene_expression IL-2_gene and NF-kappa_B_activation NF-kappa_B through CD28 requires reactive oxygen
production by 5-lipoxygenase Activation of the CD28_surface_receptor CD28 provides a major costimulatory signal for
T_cell_activation resulting in enhanced production of interleukin-2 IL-2 and cell_proliferation In
primary_T_lymphocyte we show that CD28 ligation leads to the rapid intracellular formation of
reactive_oxygen_intermediate ROI which are required for CD28-mediated_activation CD28 of the NF-kappa_B
CD28-responsive_complex CD28 and IL-2_expression IL-2 Delineation of the CD28_signaling_cascade CD28 was found to
involve protein_tyrosine_kinase_activity protein_tyrosine_kinase followed by the activation of phospholipase_A2 and
5-lipoxygenase Our data suggest that lipoxygenase_metabolite lipoxygenase activate ROI_formation ROI which then
induce IL-2 expression via NF-kappa_B_activation NF-kappa_B These findings should be useful for
therapeutic_strategies and the development of immunosuppressants targeting the CD28_costimulatory_pathway CD28

------------------------------------------------------------------------

ligand-dependent_repression of the erythroid_transcription_factor GATA-1 by the estrogen_receptor
high-dose_estrogen_administration induces anemia in mammal In chickens estrogens stimulate outgrowth of
bone_marrow-derived_erythroid_progenitor_cell and delay their maturation This delay is associated with
down-regulation of many erythroid_cell-specific_gene including band_3 band_4 1 and the
erythroid_cell-specific_histone H5 We show here that estrogens also reduce the number of erythroid_progenitor_cell
in primary_human_bone_marrow_culture To address potential mechanisms by which estrogen suppress erythropoiesis we
have examined their effects on GATA-1 an erythroid_transcription_factor that participates in the regulation of the
majority of erythroid_cell-specific_gene and is necessary for full maturation of erythrocyte We demonstrate that
the transcriptional_activity of GATA-1 is strongly repressed by the estrogen_receptor ER in a ligand-dependent
manner and that this repression is reversible in the presence of 4-hydroxytamoxifen ER-mediated_repression ER of
GATA-1_activity GATA-1 occurs on an artificial_promoter containing a single GATA-binding_site as well as in the
context of an intact_promoter which is normally regulated by GATA-1 GATA-1 and ER bind to each other in vitro in
the absence of DNA In coimmunoprecipitation_experiment using transfected COS_cell GATA-1 and ER associate in a
ligand-dependent_manner Mapping experiments indicate that GATA-1 and the ER form at least two contacts which
involve the finger region and the N-terminal_activation_domain of GATA-1 We speculate that estrogen exert effects
on erythropoiesis by modulating GATA-1_activity GATA-1 through protein-protein_interaction with the ER

------------------------------------------------------------------------

Activation of NF-kappaB in Mycobacterium_tuberculosis-_induced_interleukin-2_receptor_expression
Mycobacterium_tuberculosis interleukin-2_receptor in mononuclear_phagocyte Soluble interleukin-2_receptor-alpha
interleukin-2_receptor IL-2Ralpha has been reported to be increased in the sera of patients with advanced
tuberculosis and levels decline after therapy in accordance with improvement of radiologic_finding We investigated
expression of the IL-2Ralpha in bronchoalveolar_lavage_ BAL _cell in active_pulmonary_tuberculosis and evaluated
the mechanism Mycobacterium_tuberculosis induces in the IL-2Ralpha using the We found IL-2Ralpha_expression
IL-2Ralpha to be increased in BAL cells from involved sites of active_pulmonary_tuberculosis Expression of the
alpha-chain of IL-2Ralpha on peripheral_blood_monocyte PBM was induced by M _tuberculosis by flow cytometry
evaluation Northern analysis demonstrated increased IL-2Ralpha_gene_expression IL-2Ralpha after stimulation with M
_tuberculosis which was further induced by interferon-gamma IFN-gamma The IL-2Ralpha_promoter IL-2Ralpha containing
the nuclear_factor_kappa_B_ NF-kappaB _site nuclear_factor_kappa_B NF-kappaB was transcriptionally induced by M
_tuberculosis and this NF-kappaB site could confer inducibility to a heterologous_herpes_thymidine_kinase_ TK
_promoter thymidine_kinase thymidine by M _tuberculosis electrophoretic_mobility_shift_assay EMSA revealed specific
binding of nuclear protein to the NF-kappaB_site NF-kappaB upon induction with M _tuberculosis Using antibodies
against the p50 and p65_subunit of NF-kappaB in EMSA the involvement of both p50 and p65_protein was further
demonstrated Functional expression of the IL-2Ralpha on mononuclear_phagocyte in M _tuberculosis infection may play
an important immunomodulatory_role in the host_response

In [55]:
# Calculate KeyBERT keyword scores

# Flatten, extract, and alphebetize unique keywords
unique_raw_keywords = list({keyword for doc in keywords_corpus for keyword in doc})
unique_raw_keywords.sort()
n_unique_raw_keywords = len(unique_raw_keywords)

# Create master data frame
master_df = pd.DataFrame(data={
    'raw_keyword': unique_raw_keywords,
    'KeyBERT': np.zeros(n_unique_raw_keywords)
})

# Calculate keyword scores
for idx, raw_keyword in master_df['raw_keyword'].items():
    score = sum(1 for doc in keywords_corpus if raw_keyword in doc) / n_docs
    master_df.at[idx, 'KeyBERT'] = score


display(master_df)

                      raw_keyword   KeyBERT
0              4-hydroxytamoxifen  0.333333
1                  5-lipoxygenase  0.333333
2                   _tuberculosis  0.333333
3   active_pulmonary_tuberculosis  0.333333
4                          anemia  0.333333
..                            ...       ...
70                     repression  0.333333
71              t_cell_activation  0.333333
72         therapeutic_strategies  0.333333
73       transcriptional_activity  0.333333
74                   tuberculosis  0.333333

[75 rows x 2 columns]

In [71]:
# Recover GENIA lexical units from raw keywords

# Read in GENIA data
genia_keyword_path = '../1-preprocessing/GENIAcorpus3.02-keywords.tsv'
genia_df = pd.read_csv(genia_keyword_path, sep="\t")

# Convert lexical units to lowercase and strip '_lex' postfix
genia_df['raw_keyword'] = genia_df['lex'].str.lower().str.removesuffix('_lex')

# Add scores for lexical units
result_df = pd.merge(master_df, genia_df, on='raw_keyword', how='outer')

# Replace NaN scores with 0
result_df['KeyBERT'] = result_df['KeyBERT'].fillna(0)

# Clean up resulting data frame
result_df.rename(columns={'lex': 'term'}, inplace=True)

# Condition: If 'term' == NaN, take 'raw_keyword'; otherwise keep 'term'
# Includes non-lexical term scores.
result_df['term'] = np.where(result_df['term'].isna(), result_df['raw_keyword'], result_df['term'])

# Replace any NaNs in the 'sem' column with an empty string
# Uses empty string for the semantic class of non-lexical terms
result_df['sem'] = result_df['sem'].fillna(str())

# Drop 'raw_keywords' column
result_df.drop(columns=['raw_keyword'], inplace=True)

# Reorder columns
result_df = result_df.reindex(columns=['term', 'sem', 'KeyBERT'])

# Write to TSV
result_df.to_csv('keybert-scores.tsv', sep='\t')

display(result_df)

,term,sem,KeyBERT
0,4-hydroxytamoxifen_lex,G#other_organic_compound,0.333333
1,5-lipoxygenase_lex,G#protein_molecule,0.333333
2,_tuberculosis,,0.333333
3,active_pulmonary_tuberculosis_lex,G#other_name,0.333333
4,anemia_lex,G#other_name,0.333333
...,...,...,...
31790,gp160-induced_AP-1_complex_lex,G#protein_complex,0.000000
31791,protein_synthesis-independent_lex,G#other_name,0.000000
31792,calcium_channel_blocker_lex,G#other_organic_compound,0.000000
31793,anti-CD3-induced_interleukin-2_secretion_lex,G#other_name,0.000000
31794,T_cell_unresponsiveness_lex,G#other_name,0.000000